libs/common.js

VSCode の [ESLint Plugin](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) をインストールし、validate を有効にしたところ以下のエラーが発生しました。
```
[Error - 7:51:55 PM] Error: Failed to load plugin 'eslint-plugin-smarthr' declared in '.eslintrc.js » eslint-config-smarthr': ENOENT: no such file or directory, open '/home/f440/tsconfig.json'
Referenced from: /xxx/xxx/xxx/xxx/xxx/node_modules/eslint-config-smarthr/index.js
at Object.openSync (fs.js:476:3)
at Object.readFileSync (fs.js:377:35)
```
Spotlight などで VSCode を起動した場合、環境変数 `PWD` はホームディレクトリになり、tsconfig.json が見つけられず上記エラーになっているようです。実際にプロセスが動いているディレクトリを取得するようにして対処しました。

tsconfig.json のパス判定方法を修正

---

rules/redundant-name.js

- 1keywordで構成されている名称は省略しないように修正
- 例: `src/entities/crew.rb` ファイル内の `class Entity` は省略しなくて良い

update: redudant-name の条件を調整する

---

README.md
libs/common_domain.js
package.json
rules/prohibit-import.js
rules/redundant-name.js
yarn.lock

- テスト環境を適用できるようにするため、optionでfunction を渡している箇所を調整します
- domain判断用の関数をoptionではなく、rule内で持つように調整
- keyword生成用の処理をoptionではなく、rule内で持つように調整
- redundant-nameの修正例として出力される名前を関数で生成するのではなく、修正用設定を指定するように修正

BREAKING CHANGE: テストを適用可能にするため、function optionを取り除く

---

README.md
rules/jsx-start-with-spread-attributes.js

- jsx-start-with-spread-attributes に fix option を追加
- 意図して値を spread attributes で上書きしている可能性もあるため、 --fix での自動修正時に上書きするかどうかはユーザーが選べるようにしました

chore: jsx-start-with-spread-attributes に fix optionを追加

---

README.md
rules/require-barrel-import.js

- Barrelがある（少なくともexportしておくべきindexファイルが有る）のに直接importしてしまっている場合に教えてくれるruleを作成します。

feat: add require-barrel-import rule

---

README.md
rules/a11y-anchor-has-text.js
rules/a11y-icon-button-has-name.js
test/a11y-anchor-has-text.js

- a、 `AnchorButton` などのchildren内にテキストとなるものがない場合、エラーとなるルールを追加します
- 以前作成済みの `Button 内にアイコンのみで代替テキストがない場合エラーとする` ルールにalt指定されていればOKとする修正を加えます

feat: リンク要素内にテキストが設定されていない場合、エラーとなるルールを追加する

---

rules/redundant-name/index.js

- 型名チェックの処理は他の名称チェックとLogicが違うため、allowedNamesによる許可される名称の設定が有効にならないバグが発生していたため修正します

fix: redundant-name rule の allowedNames オプションが適用されないバグがあったため修正する

---

rules/format-import-path/README.md
rules/no-import-other-domain/README.md
rules/redundant-name/README.md
rules/redundant-name/index.js
rules/require-barrel-import/README.md

- root取得用の処理を調整した結果がREADMEに反映しました
- tsconfig.jsonの compilerOptions.paths に設定するrootパスを `@/*` だけではなく `~/*` でも登録可能にしました

chore: update README

---

rules/prohibit-import/index.js
rules/require-import/index.js

fix: require-import, prohibit-import: report message の一部でテンプレート文字列がそのまま出力されてしまう事があるバグを修正

---

rules/a11y-clickable-element-has-text/index.js
rules/a11y-image-has-alt-attribute/index.js

画像のaltチェック似バグが見つかったので修正します
- 特定の記法の際にエラーになってしまうバグを修正
- 特定の状況化でalt属性が未指定扱いになってしまうバグを修正

fix: 画像系コンポーネントが代替テキスト属性を持つかチェックする際にエラーになるパターンを修正

---

rules/a11y-prohibit-input-placeholder/README.md
rules/a11y-prohibit-input-placeholder/index.js
test/a11y-prohhibit-input-placeholder.js

- input, textarea でplaceholder属性をヒント用要素、tooltipなどに変更することを促すルールを作成しました

feat: add a11y-prohibit-input-placeholder rule.

---

libs/common_domain.js

- 正規表現でファイルパスからディレクトリまでのパスを生成するロジックが存在していたが、そもそも正規表現が不要だった
- ディレクトリ名に `.` が含まれている場合、バグるので調整する

fix: domain系ルールのチェック対象ファイルのdirを取得するロジックから正規表現を取り除く

---

rules/a11y-clickable-element-has-text/README.md
rules/a11y-clickable-element-has-text/index.js
test/a11y-clickable-element-has-text.js

- ReactFragmentがclickable要素の中に存在すると、ソレ以下の要素のチェックがスキップされてしまうバグを修正
- `role` と `aria-label` が同時に指定された要素がclickable要素以下に存在する場合はテキストありと判定するように修正
- テキストを持つコンポーネントを設定で指定可能にした

fix: a11y-clickable-element-has-textのバグを修正する

---

rules/a11y-image-has-alt-attribute/index.js
test/a11y-image-has-alt-attribute.js

- svgタグ内のimageタグはalt属性を持たず、代替テキストの設定も不要のため、誤検知しないように修正したい

fix: a11y-image-has-alt-attribute が svg > image を誤検知してしまうバグを修正する

---

README.md
rules/prohibit-path-within-template-literal/README.md
rules/prohibit-path-within-template-literal/index.js
test/prohibit-path-within-template-literal.js

- URIを管理するオブジェクトを template-literal で囲むことを禁止するルールを追加します
- このルールを有効にすることにより、以下のメリットがあります
- queryStringなどのURIの一部の生成ロジックが対象オブジェクトに集約するため、責務が分散せず、対象オブジェクトを見れば生成されるURLのパターンが把握しきれるようになります

feat: add prohibit-path-within-template-literal rule.

---

rules/no-import-other-domain/README.md
rules/no-import-other-domain/index.js
rules/require-barrel-import/README.md
rules/require-barrel-import/index.js

- ignoresオプションを追加します
- ignore commentに頼らなくて良くなるため、コードをクリーンに保ちたい場合などに利用できます
- ignoresオプションより詳細にimportを制御出来るよう、arrowImportsオプションを追加します
```
allowedImports: {
'/test/msw/handlers': { // ファイルの正規表現
// import制御するファイル(相対パスを指定する場合は.eslintrc.jsからの相対パス)
'@/redux/pages/admin/crewCustomFieldTemplateGroups/index/repositories/mock': ['mocks', 'getExpect200'], // valueは true, false, string[] で string[] を指定すると、個別にimportを許可できる
},
},
```

feat: ignores option for no-import-other-domain and require-barrel-import

---

rules/prohibit-path-within-template-literal/index.js

- `hogehoge${Obj}` のようにプロパティ参照をしないパターンの場合にエラーになってしまう事があったため修正します

fix: prohibit-path-within-template-literalのpathオブジェクト名の解析の際、エラーになるパターンがあったため修正する

---

github/CODEOWNERS

経緯は以下と推測します。
- #17 で `github/CODEOWNERS` が生まれた。
- 正しくは `github/CODEOWNERS` ではなく `.github/CODEOWNERS` なので #18 で移動した。ただし、`.github/CODEOWNERS` だけ add して `github/CODEOWNERS` を rm しなかったため、両方残ってしまった。

fix: ディレクトリの削除もれ対応

---

rules/redundant-name/README.md
rules/redundant-name/index.js

feat: redundant-name にignores オプションを追加

---

libs/format_styled_components.js
test/a11y-clickable-element-has-text.js
test/a11y-image-has-alt-attribute.js
test/a11y-input-has-name-attribute.js
test/a11y-prohhibit-input-placeholder.js
test/a11y-trigger-has-button.js

- `const Hoge = styled.select(() => any)` や `const Hoge = styled(Select)(() => any)` のように `TaggedTemplateExpression` が存在しないパターンの場合命名規則のルール外になっていたため対応
- 同様に `const Hoge = styled('select')` の場合も対象外となっていたため対応

feat: a11y系ruleのコンポーネント名チェックが漏れているパターンが存在したため調整

---

README.md
rules/a11y-anchor-has-href-attribute/README.md
rules/a11y-anchor-has-href-attribute/index.js
test/a11y-anchor-has-href-attribute.js

- `hrefが設定されていないanchor要素` を検出し、設定することを促すルールを追加します
- これにより以下の問題が解決します
- URLの変更が伴わない動作を設定する要素は基本的にaよりbuttonが適切なため、差し替えを促せる
- URLの変更を伴う動作を設定している場合はhrefを設定することにより、キーボード操作やコンテキストメニューでの遷移に対応できる

feat: a11y-anchor-has-href-attribute を追加

---

rules/best-practice-for-remote-trigger-dialog/README.md
rules/best-practice-for-remote-trigger-dialog/index.js
test/best-practice-for-remote-trigger-dialog.js

- id属性の指定必須であることをチェックするロジックの対象を絞ります
- RemoteTriggerXxxxDialog系は MessageDialog, ModelessDialog が追加される予定なのでそれに合わせて対象を絞る処理を調整
- id未指定の場合、実行エラーになっていた問題を修正しました

fix!: best-practice-for-remote-trigger-dialog にリネーム & 特定パターンでバグが起きる問題を修正する

---

libs/common.js

- tsconfigファイルのcompilerOptions.pathsに依存する処理のチェックを変更

fix: replacePathsの生成時、tsconfigにcompilerOptions.pathsが設定されていなければエラーになるように修正

---

README.md
rules/a11y-heading-in-sectioning-content/README.md
rules/a11y-heading-in-sectioning-content/index.js
test/a11y-heading-in-sectioning-content.js

- smarthr-ui/SectioningContent の追加に合わせて推奨する使い方を伝えるため、ルールを作成します
- 基本的に `同一コンポーネント内で範囲が明確ではないHeadingが複数ある場合、エラーになる` というルールです
- 単一の場合、範囲指定は外部コンポーネントで行われている可能性があるため、エラーにはならないようにしています

feat: a11y-heading-in-sectioning-contentを追加

---

rules/a11y-heading-in-sectioning-content/index.js
test/a11y-heading-in-sectioning-content.js

`const HogeHeading = () => <Heading tag="h2">hoge</Heading>` のようなコンポーネントを作っている場合、誤検知されてしまっていたため、修正します

fix: a11y-heading-in-sectioning-contentのHeadingアウトライン未指定の誤検知を修正する

---

rules/a11y-heading-in-sectioning-content/index.js
test/a11y-heading-in-sectioning-content.js

以下のような場合、本来検知してほしくないものがエラーになってしまっていたので修正しました
```
export const HogeHeading = () => <Heading>any</Heading>
```
exportがついていないパターンは問題なく除外されていましたが、export有りのパターンは未対応だったのでテストも追加しています

fix: a11y-heading-in-sectioning-content で Heading系コンポーネントの拡張をexportしている場合、正しく除外されないバグを修正

---

libs/common.js
rules/format-import-path/README.md
rules/no-import-other-domain/README.md
rules/redundant-name/README.md
rules/require-barrel-import/README.md

- tsconfig.json の設置ディレクトリを変更可能にするため、.eslintrc.js の parserOption.project を参照するように変更します

feat: .eslintrc.js などの設定からparserOptions.project が設定されている場合、tsconfig.jsonの読み込み先を変更する

---

rules/a11y-clickable-element-has-text/README.md
rules/a11y-clickable-element-has-text/index.js
test/a11y-clickable-element-has-text.js

- `XxxText` のようなコンポーネントをa, button内に設置することはよく有り、それらをいちいち `componentsWithText` で設定することは面倒なのでデフォルトでエラーにならないように調整します。
- `XxxxTextWithYyyy` のような場合もエラーにならないようにすることも検討しましたが、それほど発生頻度が高くないようなので今回は対応しません

feat: a11y-clickable-element-has-text のチェック時、リンク内部に名称の末尾がTextがつくコンポーネントがある場合、チェックを通過するように修正

---

rules/best-practice-for-date/index.js

- 固定の日付を扱う場合 `new Date('YYYY/MM/DD')`　のように日付文字列を直接渡してしまう場合がある
- 問題になる可能性は低いが、他コードとの一貫性を保つため、 `new Date(YYYY, MM - 1, DD)` に置換するようにfixerを追加します
- 同様に `Date.parse('YYYY-MM-DD')` のような場合も `new Date(YYYY, MM - 1, DD).getTime()` に置換します

feat: best-practice-for-dateを調整し、`new Date("YYYY/MM/DD")` のように日付文字列を直接設定している場合 `new Date(YYYY, MM - 1, DD)` に置き換えるfixerを追加

---

rules/a11y-anchor-has-href-attribute/README.md
rules/a11y-anchor-has-href-attribute/index.js
rules/a11y-image-has-alt-attribute/README.md
rules/a11y-image-has-alt-attribute/index.js
rules/a11y-input-has-name-attribute/README.md
rules/a11y-input-has-name-attribute/index.js
test/a11y-anchor-has-href-attribute.js
test/a11y-image-has-alt-attribute.js
test/a11y-input-has-name-attribute.js

- a11y-xxxx-has-yyyy-attribute は `spread attribute に yyyy属性が含まれている` 場合に対応出来なかった
- optionで `checkType: 'smart'` を指定した場合、対象要素に spread attribute が指定されている場合はcorrectになるようにします

feat: feat: a11y-xxx-has-yyy-attributeにcheckTypeオプションを追加にcheckTypeオプションを追加

---

libs/format_styled_components.js
rules/a11y-anchor-has-href-attribute/index.js
rules/a11y-clickable-element-has-text/index.js
rules/a11y-heading-in-sectioning-content/index.js
rules/a11y-image-has-alt-attribute/index.js
test/a11y-anchor-has-href-attribute.js
test/a11y-clickable-element-has-text.js
test/a11y-heading-in-sectioning-content.js
test/a11y-image-has-alt-attribute.js

- styled-componentsでコンポーネントを拡張する際、機能・役割を勘違いしそうな名称がついている場合エラーにします
- 例: `const HogeAnchor = styled.div` はNG
- 例: `const HogeAnchorWrapper = styled.div` はOK

feat: a11y系ruleにstyled-componentsで既存のコンポーネントなどを拡張する際、誤検知が発生しそうな名称が設定されている場合はエラーにする機能を追加

---

rules/a11y-delegate-element-has-role-presentation/index.js
test/a11y-delegate-element-has-role-presantation.js
yarn.lock

- 三項演算子など、expression内でJSXElementが存在する場合、インタラクティブな要素かどうかを判定できるように修正
- エラー時の修正案をより具体的に修正
- smarthr-uiなどのライブラリ向けとして、roleがpresentation以外の意味があるものが指定されている場合にエラーにならないように修正

fix: a11y-delegate-element-has-role-presentation のインタラクティブな要素の判定を調整する

---

rules/a11y-input-in-form-control/index.js
test/a11y-input-in-form-control.js

- XxxRadioButtons，YyyyCheckBoxes などのlabel付き入力要素を複数持つことが推測されるコンポーネント名を判定し、エラーなどを適切にハンドリングするように修正します

feat: a11y-input-in-form-controlでlabelが設定されている可能性が高いRadio, Checkboxの複数形コンポーネントを正しく判定できるようにする

---

libs/format_styled_components.js
rules/best-practice-for-button-element/README.md
rules/best-practice-for-button-element/index.js
test/best-practice-for-button-element.js

- button要素のtype属性のデフォルト値が 'submit' であることが `form要素でラップしている場合clickでsubmitされてしまう` という開発者が意図しづらい問題を引き起こすことがあるため、防ぎたい
- styled-componentsなどで `HogeButton` ようにbutton要素そのままではない場合などに顕著に指定ミスが起こりがち
- smarthr-ui/Buttonなどは上記問題に対応するため、type属性のデフォルト値をbuttonにしてあるため、以下のチェックを行うようにしたい
- button要素を直接利用する場合はtype属性の設定を必須にする
- HogeButtonなどのように、コンポーネントの場合はチェックしない
- styled-componentsでstyled.bottonの直接利用を禁止する

feat: best-practice-for-button-elementを追加

---

rules/a11y-anchor-has-href-attribute/README.md
rules/a11y-anchor-has-href-attribute/index.js
rules/a11y-image-has-alt-attribute/README.md
rules/a11y-image-has-alt-attribute/index.js
rules/a11y-input-has-name-attribute/README.md
rules/a11y-input-has-name-attribute/index.js
test/a11y-anchor-has-href-attribute.js
test/a11y-image-has-alt-attribute.js
test/a11y-input-has-name-attribute.js

- smartオプションではルールの実体が分かりづらかったため、allow-spread-attributesに変更します

fix!: spread attributesが指定されている場合、ruleをcorrectにする smart オプションを allow-spread-attributes オプションにリネームする

---

rules/a11y-numbered-text-within-ol/index.js

- width, height系の属性以外にもletterSpacingなどが設定できるため、属性名ではなく、値で除外するようにロジックを変更します

fix: a11y-numbered-text-within-olのチェックで、属性の値でstyleに数値を指定しているような値の場合、無視する

---

rules/a11y-heading-in-sectioning-content/index.js
test/a11y-heading-in-sectioning-content.js

- 独自のSectioningContent系を拡張したコンポーネントがtitle, heading属性を持っている場合、headingを内包している扱いになるようルールを調整します

feat: a11y-heading-in-sectioning-contentで title, もしくはheading属性がSectioningContent系コンポーネントに設定されている場合、headingがあると判定するように修正

---

README.md
rules/a11y-replace-unreadable-symbol/README.md
rules/a11y-replace-unreadable-symbol/index.js
test/a11y-replace-unreadable-symbol.js

- 一部記号はスクリーンリーダーで読み上げられない、もしくは記号名そのままで読み上げられてしまい、意図が正しく伝えられない場合があります
- それらの記号を適切に読み上げられるコンポーネントに置き換えることを促すルールです

feat: a11y-replace-unreadable-symbol

---

README.md
rules/a11y-prohibit-input-maxlength-attribute/README.md
rules/a11y-prohibit-input-maxlength-attribute/index.js
test/a11y-prohibit-input-maxlength-attribute.js

`<input>` `<textarea>` 及びその拡張コンポーネントに対する `maxLength` 属性の使用を禁止するルール (`a11y-prohibit-input-maxlength-attribute`) を追加します。
`maxlength` は、テキストをコピペした際に制限以上の文字列が勝手に切り捨てられる使用でユーザビリティ・アクセシビリティ上の問題があるため
関連ルールを模倣しながら、モブプロで実装するなど
プロダクト側に反映させて、正しく検知できることを確認。

feat: a11y-prohibit-input-maxlength-attribute

---

rules/best-practice-for-layouts/index.js
test/best-practice-for-layouts.js

Stackコンポーネントにgap={0}が指定されている場合、基本的にStackコンポーネントは無意味、もしくはdivで良いため、エラーにするようにします

feat: best-practice-for-layoutsでStackコンポーネントにgap={0}が指定されている場合、適切に置き換え・または削除を促すように修正

---

rules/a11y-input-in-form-control/index.js
test/a11y-input-in-form-control.js

`a11y-input-in-form-control` のルールを修正し、三項演算子内の入力要素だった場合に、入力要素が複数あると誤認されないようにします。
以下のようなコードで False Positive が発生する。
```tsx
<FormControl>
{ date ? <DateInput /> : <Input /> }
</FormControl>
```
実際は DateInput と Input どちらかしか描画されないが、FormControl 内に複数の入力要素があると警告が出てしまう。
走査時に三項演算子の有無をチェックし、それに応じて入力要素数を正しく数えるようにする

fix:  <FormControl> 内に三項演算子がある場合に、入力要素が複数あると誤認されないようにする

---

rules/a11y-delegate-element-has-role-presentation/index.js

* SmartHR UIの `FilterDropdown` コンポーネントを利用し `onClick` 属性に値を渡しても `smarthr/a11y-delegate-element-has-role-presentation` ルールに抵触しないようにしたいです
* `FilterDropdown` コンポーネントは内部的に `onClick` 属性の値を [`Button` コンポーネントにフォワーディングしています](https://github.com/kufu/smarthr-ui/blob/187f2d01b294fe8c6fc92575032fb2a09dbc98eb/packages/smarthr-ui/src/components/Dropdown/FilterDropdown/FilterDropdown.tsx#L146)
* 最終的にインタラクティブな要素に値が渡されている以上は本ルールの規制対象にならないと考えています
* `smarthr/a11y-delegate-element-has-role-presentation` ルールが期待するコンポーネント名に `FilterDropdown` を追加しました

fix: 適切にonClick属性を利用しているケースを通したい！

---

rules/design-system-guideline-prohibit-double-icons/README.md
rules/design-system-guideline-prohibit-double-icons/index.js
test/design-system-guideline-prohibit-double-icons.js

- [提案スレ](https://kufuinc.slack.com/archives/CJEUZ4MS6/p1718345555119859?thread_ts=1717387640.101129&cid=CJEUZ4MS6)

feat: ButtonやTextLinkコンポーネントにprefix, suffixの両属性を同時に設定できないルールを追加

---

rules/a11y-clickable-element-has-text/index.js
test/a11y-clickable-element-has-text.js
test/a11y-delegate-element-has-role-presantation.js

smarthr-ui/Icon など、text属性をもつコンポーネントの対応を追加します

fix: a11y-clickable-element-has-text でtext属性を持つコンポーネントが存在する場合、真となるように修正

---

rules/design-system-guideline-prohibit-double-icons/README.md

IncorrectとCorrectのサンプルが同一になってしまっていたので修正

fix: README.md内のIncorrect examplesを修正

---

README.md
rules/a11y-prohibit-sectioning-content-in-form/README.md
rules/a11y-prohibit-sectioning-content-in-form/index.js

- form, fieldset, smarthr-ui/Fieldset 以下でSectioningContent(section, aside, article, nav)が利用されている場合、smarthr-ui/Fieldsetに置き換えることを促すルールを追加します
- このルールを適用することで以下のようなメリットがあります
- form要素内からHeadingが取り除かれ、Fieldsetに統一されることにより、見出しを表現する要素がlegend, label要素のみになります
- これによってマークアップのルールが統一され、スクリーンリーダーのジャンプ機能などの利便性が向上します
- ジャンプ機能ではheading, legendは区別されるため統一されることで操作方法が単純化されます
- a11y-form-control-in-form と組み合わせることでより厳密なフォームのマークアップを行えます

feat: a11y-prohibit-sectioniing-content-in-formを追加
