rules/redundant-name.js

- class の prop, methodも命名規則の対象になるように修正
- enum も 変数扱いにして修正対象とする

update: redundant-name: classのprop, method & enum にもformatを適用可能にする

---

libs/common_domain.js
rules/format-import-path.js

- https://github.com/kufu/eslint-plugin-smarthr/pull/2 で対応した `process.env.PWD -> process.cwd()` の対応を全体で行います。

fix: process.env.PWD -> process.cwd()

---

.gitignore
LICENSE
package.json
yarn.lock

整えました！
マージされたらリリースします 🚀
- リリース内容確認コマンド
- `yarn release:dryrun --first-release`
- リリースコマンド
- `yarn release --first-release`

npm リリース用に整えた

---

README.md
rules/redundant-name.js

- redundant-name を更新しました
- Type のpropsを省略対象とするように修正
- 関数、メソッドの引数を省略対象とするように修正
- 修正例を複数出すパターンを追加
- 修正例をユーザーが操作できるようにoptionにfunctionを設定できるように修正

feat: update redundant-name

---

rules/prohibit-import.js

- 不要になったschemaを削除
- 禁止importの名称埋め込みをマスタッシュ記法に変更

update: prohibit-ruleを修正(import禁止対象の埋め込みをマスタッシュ記法にする)

---

jest.config.js
package.json
rules/prohibit-import.js
test/prohibit-import.js
yarn.lock

- 独自のeslintルールのテストをできるようにテスト環境を用意しました
- prohibit-import ルールにテストを追加しています
- テストが落ちる部分があったのでリファクタリングしています
- メッセージをカスタマイズできるようにSchemaに変更を加えています

BREAKING CHANGE: prohibt-import ruleにテストを追加する

---

README.md
rules/prohibit-import.js
rules/require-import.js
test/prohibit-import.js
test/require-import.js
yarn.lock

- 特定のimportを強制させたい場合のルール、 `require-import` を追加しました
- `require-import` のoptionのフォーマットと `prohibit-import` のフォーマットを揃えました

BREAKING CHANGE: add require-import & update prohibit-import

---

rules/require-barrel-import.js

- barrelファイルの場合、チェックをしない仕様にしていましたが、ディレクトリ構成次第で検知できない場合があったため修正しました
- ファイルまでのpathに複数のbarrelファイルが存在する場合、最もrootに近いものからimportを促すように修正しました

fix: require-barrel-import修正（barrelファイルが複数存在する場合、一番親に当たるファイルを検知する）

---

libs/format_styled_components.js
rules/a11y-clickable-element-has-text.js
rules/a11y-image-has-alt-attribute.js
rules/a11y-trigger-has-button.js
test/a11y-image-has-alt-attribute.js
test/a11y-trigger-has-button.js

- 画像はaltを持つこと強制するルールを作成
- DialogTrigger, DropdownTrigger は直下にButtonコンポーネントを持つことを強制するルールを作成

A11系ルール: 画像altとXxxxTriggerの設定を追加

---

README.md
rules/format-translate-component.js
test/format-translate-component.js

- 翻訳用プラグインの適用方法を定めるルールです
- コードレビュー
- `yarn jest`

feat: add rules format-translate-component

---

libs/format_styled_components.js

- アクセシビリティ系ruleで利用しているstyled-componentsの実行結果の変数名チェックですが、styled-componentsの実行結果を変数に代入しないパターンが存在したため対応します

fix: a11y-xxxx: styled(Hoge)の実行結果を変数に代入しないパターンに対応する

---

rules/a11y-clickable-element-has-text/index.js
rules/a11y-image-has-alt-attribute/index.js
rules/a11y-trigger-has-button/index.js
rules/best-practice-for-date/index.js
rules/jsx-start-with-spread-attributes/index.js
yarn.lock

- meta.type を problem に変更し、優先的に修正すべき内容であることを明示します

feat: 修正しなければ問題が起きる可能性があるruleのmeta.typeをproblemに修正

---

rules/a11y-prohibit-input-placeholder/index.js

- FieldSet, ComboBox もplaceholder属性を非推奨としたい
- チェック対象に含めます

feat: placeholder非推奨の対象に FieldSet, ComboBox も含める

---

README.md
rules/require-declaration/README.md
rules/require-declaration/index.js
test/require-declaration.js

- 対象ファイルに宣言してほしい、変数・関数・class・型などを定義するルールです

feat: add require-declaration rule

---

README.md
rules/a11y-prohibit-input-placeholder/index.js
test/a11y-prohhibit-input-placeholder.js

- ComboBoxに defaultItem, dropdownHelpMessage optionが追加されたので、それらの使い分けを表示するようにします

update: a11y-prohibit-input-placeholder を最新のComboBoxに対応させる

---

rules/redundant-name/index.js

fix: ファイルが複数の.を保つ場合（例 xxx.test.tsx）正常に動作しないバグを修正する

---

libs/format_styled_components.js
rules/a11y-clickable-element-has-text/index.js
rules/a11y-image-has-alt-attribute/index.js
rules/a11y-prohibit-input-placeholder/index.js
rules/a11y-radio-has-name-attribute/index.js
rules/a11y-trigger-has-button/index.js
rules/best-practice-for-date/index.js
rules/format-import-path/index.js
rules/format-translate-component/index.js
rules/jsx-start-with-spread-attributes/index.js
rules/no-import-other-domain/index.js
rules/prohibit-export-array-type/index.js
rules/prohibit-file-name/index.js
rules/prohibit-import/index.js
rules/prohibit-path-within-template-literal/index.js
rules/redundant-name/index.js
rules/require-barrel-import/index.js
rules/require-declaration/index.js
rules/require-export/index.js
rules/require-import/index.js
rules/trim-props/index.js

- messageIdを利用するエラーメッセージ表示が、無意味なため削る

chore: messageIdを指定する形式が、意味のないフォーマットしかないため修正する

---

rules/a11y-anchor-has-href-attribute/README.md
rules/a11y-anchor-has-href-attribute/index.js
test/a11y-anchor-has-href-attribute.js

- next.js, react-router の Linkコンポーネントを利用するパターンに対応しました

feat: next.js, react-routerのLinkコンポーネントに対応するオプションを追加

---

rules/require-barrel-import/index.js

- 定数やループの事前に計算可能なものを調整することで実行速度をupします

chore: require-barrel-importをリファクタリング

---

rules/a11y-delegate-element-has-role-presentation/index.js
test/a11y-delegate-element-has-role-presantation.js

- role="presentation" が設定されている要素内でアクティブな要素を検索する処理をより厳密に行うように修正
- role="slider" が設定されている要はアクティブな要素として扱うように修正

fix: a11y-delegate-element-has-role-presentationでインタラクティブな要素のチェック処理を厳密に行う

---

README.md
index.js
rules/a11y-form-control-in-form/README.md
rules/a11y-form-control-in-form/index.js
test/a11y-form-control-in-form.js

- FormControl, Fieldset, fieldsetを利用する場合、form要素で囲むことを促すルールを追加します

feat: a11y-form-control-in-formルールを追加

---

rules/best-practice-for-layouts/index.js
test/a11y-anchor-has-href-attribute.js
test/a11y-clickable-element-has-text.js
test/a11y-delegate-element-has-role-presantation.js
test/a11y-form-control-in-form.js
test/a11y-heading-in-sectioning-content.js
test/a11y-image-has-alt-attribute.js
test/a11y-input-has-name-attribute.js
test/a11y-input-in-form-control.js
test/a11y-numbered-text-within-ol.js
test/a11y-prohhibit-input-placeholder.js
test/a11y-prohibit-useless-sectioning-fragment.js
test/a11y-trigger-has-button.js
test/best-practice-for-button-element.js
test/best-practice-for-date.js
test/best-practice-for-layouts.js
test/best-practice-for-remote-trigger-dialog.js
test/format-translate-component.js
test/prohibit-file-name.js
test/prohibit-import.js
test/prohibit-path-within-template-literal.js
test/require-declaration.js
test/require-export.js
test/require-import.js

fix: best-practice-for-layoutsで "a?.map(function)" のようにchainを使っている場合正しく検知できなかった問題を修正

---

README.md

chore: `design-system-guideline-prohibit-double-icons` をREADME.mdに追加

---

rules/a11y-delegate-element-has-role-presentation/index.js
rules/a11y-input-has-name-attribute/index.js
rules/a11y-input-in-form-control/index.js
rules/a11y-prohibit-input-placeholder/index.js
test/a11y-delegate-element-has-role-presantation.js
test/a11y-input-in-form-control.js
test/a11y-prohhibit-input-placeholder.js

smarthr-ui/TimePickerをa11y系ルールの対象になるように修正します

feat: a11y系ルールの対象にsmarthr-ui/TimePickerを追加する

---

rules/a11y-input-in-form-control/index.js

- type="hidden" が指定されている場合の対応を追加します

feat: a11y-input-in-form-controlでtype="hidden"の場合の判定を追加

---

rules/a11y-input-in-form-control/index.js
test/a11y-input-in-form-control.js

`a11y-input-in-form-control.js`のルールに`WarekiPickear`を追加しました。

feat: WarekiPickerをa11y-input-in-form-controlルールに追加
